name = "jejuweb"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# Workers 라우트 설정
routes = [
  { pattern = "jejuweb.k97460300.workers.dev", zone_name = "" }
]

[vars]
# 필요한 환경 변수가 있다면 여기에 추가
